language: node_js
git:
  submodules: false
os: linux
dist: xenial
sudo: enabled
install:
# avoid default npm install
- true
script:
- "./launch --bypass_emscripten --dry --npm update"
- npm run lint-check
- npm test

